export { default as ImageSection } from './ImageSection/ImageSection'
export { default as HeroSection } from './HeroSection/HeroSection'
export { default as ProjectsSection } from './ProjectsSection/ProjectsSection'
export { default as TextSection } from './TextSection/TextSection'
export { default as UserStoriesSection } from './UserStoriesSection/UserStoriesSection'
export { default as VectorSection } from './VectorSection/VectorSection'
