export { default as ApproachSection } from './ApproachSection/ApproachSection'
export { default as ConclusionSection } from './ConclusionSection/ConclusionSection'
export { default as MotivationSection } from './MotivationSection/MotivationSection'
export { default as HeroSection } from './HeroSection/HeroSection'
export { default as ToolsSection } from './ToolsSection/ToolsSection'
