import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'

import { PageHeader } from './components'

import './globals.scss'

const mulish = Mulish({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body className={`${mulish.className} sm:px-4 lg:px-10`}>
        <PageHeader />

        {children}
      </body>
    </html>
  )
}
