import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'

import './globals.scss'

const mulish = Mulish({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang={'en'}>
      <body className={mulish.className}>{children}</body>
    </html>
  )
}

export { metadata }
export default RootLayout
