import { Mulish } from 'next/font/google'
import type { Metadata } from 'next'

import '@/styles/globals.scss'

const mulish = Mulish({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  const pageSections = [
    { path: '', label: 'Hi' },
    { path: '', label: 'Projects' },
    { path: '', label: 'About' },
    { path: '', label: 'Contact' },
  ]

  return (
    <html lang='en'>
      <body className={mulish.className}>{children}</body>
    </html>
  )
}

export default RootLayout
